### ISSUE TITLE
Encountered value at /event/time that does not meet the required constraints.

### ISSUE THREAD

**Issue by lrdluis** [maxmind/minfraud-api-java#26]
Using minfraud version 1.5.0, when we call method score and we pass the time parameter as date, we received this warning:
"code":"INPUT_INVALID","warning":"Encountered value at /event/time that does not meet the required constraints.","input_pointer":"/event/time"

**Comment by oschwald** [comment]
Thanks for reporting this! It is fixed in 1.5.1, which should be available on Maven Central mirrors in several hours.

**Comment by lrdluis** [comment]
Thanks!
