### ISSUE TITLE
cannot deserialize FactorsResponse object from json

### ISSUE THREAD

**Issue by miche-atucha** [maxmind/minfraud-api-java#28]
I'm caching a FactorsResponse object to json (with provided method "toJson"), but when i try to read the json to the FactorsResponse object (using Jackson ObjectMapper.readValue) i get the following error: 
**com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.maxmind.geoip2.record.City, problem: No 'injectableValues' configured, can not inject value with id [locales]
 at [Source: {JSON-HERE}; line: 1, column: 475] (through reference chain: com.maxmind.minfraud.response.FactorsResponse["ip_address"]->com.maxmind.minfraud.response.IpAddress["city"])**

is there another way to read the json?

**Comment by horgh** [comment]
Hi @miche-atucha. It sounds like you may need to set up an `InjectableValues`. Something like this may work:

```
            ArrayList locales = new ArrayList();
            locales.add("en");
            InjectableValues inject = new Std().addValue("locales", locales);
            FactorsResponse f = mapper.readerFor(FactorsResponse.class).with(inject).readValue(myFactorsJSON);
```

**Comment by miche-atucha** [comment]
great! thanx!
